name: Generate Snake

on:
  schedule:
    # Executar a cada 24 horas
    - cron: "0 0 * * *"
  
  # Permite executar este workflow manualmente na aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - uses: actions/checkout@v2
      
      # Gera a animação da cobra
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: WillMachado67
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Envia os arquivos gerados para a branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}